version: '3'

services:
  chat-redes:
    image: mongo
    container_name: chat-redes
    restart: always
    environment:
      MONGO_INITDB_DATABASE: chat-redes
      MONGO_INITDB_ROOT_USERNAME: chat-redes
      MONGO_INITDB_ROOT_PASSWORD: password123
    
    ports:
    - "27019:27017"
  
    
   

